### PR TITLE
Same erasure, this is not needed.

### PR DESCRIPTION
**Pull request by Victorious3**

### CODE REVIEW

**Comment by coolsquid** [comment]
There was some reason I added this...

**Comment by Victorious3** [comment]
There is no reason. No. Reason. At. All.

**Comment by coolsquid** [comment]
I'll fix it locally, as I don't feel like messing up the repo.

**Comment by Victorious3** [comment]
`git pull` exists, you know?

**Comment by coolsquid** [comment]
I've changed that class today. If you want merge errors and corrupted repos, then play around with your own repos.

**Pull request closed without merging**
